-- =============================================================================
-- 110_ciiu_completo_d088.sql -- Agente A1, submodulo D-088 (Tarea A)
--
-- Amplia el catalogo `ciiu_activity` con las CLASES CIIU de 4 digitos
-- (Rev. 4 A.C. adaptada para Colombia, DANE) que faltaban, para que la carga
-- masiva de ICA por municipio de D-088 pueda resolver `ciiu_activity_id` por
-- codigo sin fallar todas las filas.
--
-- FUENTE Y ALCANCE DE LA VERIFICACION:
--   - El punto de partida son los codigos del Excel de ejemplo entregado por
--     el usuario (archivos-masivos/EJEMPLO_D088_parametrizacion_ica.xlsx).
--   - De ese archivo se toman UNICAMENTE los codigos de 4 digitos, que son la
--     estructura de clase de la CIIU Rev. 4 A.C. (informacion publica
--     verificable: Resolucion DANE que adopta la CIIU Rev. 4 A.C.).
--   - El Excel tambien traia ~100 codigos de 5 digitos (subclases propias del
--     Distrito de Bogota / DIAN, p. ej. 74901, 85591) y una celda con valor
--     "85232/8551": NO se cargan aqui. El CHECK `ciiu_codigo_ck` exige 4
--     digitos y esas subclases no son CIIU nacional. Quedan registradas en
--     ESTADO_PROYECTO.md como pendientes de decision de esquema (V-5).
--   - `seccion` se deriva de la division (2 primeros digitos) segun los rangos
--     oficiales de secciones de la CIIU Rev. 4 A.C.
--
-- PENDIENTE DE VERIFICACION HUMANA (anotado en ESTADO_PROYECTO.md):
--   Las DESCRIPCIONES provienen del Excel del usuario y pueden estar
--   abreviadas respecto del texto oficial DANE. El codigo y su ubicacion
--   (seccion/division) si son verificables. Falta contrastar el literal de
--   cada descripcion contra la publicacion oficial de la CIIU Rev. 4 A.C.
--
-- Identidad estable, sin vigencia y sin norma_respaldo (la tabla no las
-- tiene). Idempotente: NOT EXISTS por codigo, no pisa filas ya sembradas.
-- =============================================================================

INSERT INTO ciiu_activity (tenant_id, company_id, codigo, nombre, seccion, division)
SELECT NULL, NULL, v.codigo, v.nombre, v.seccion, v.division
FROM (VALUES
  ('0111', 'Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas', 'A', '01'),
  ('0112', 'Cultivo de arroz', 'A', '01'),
  ('0113', 'Cultivo de hortalizas, raíces y tubérculos', 'A', '01'),
  ('0114', 'Cultivo de tabaco', 'A', '01'),
  ('0115', 'Cultivo de plantas textiles', 'A', '01'),
  ('0119', 'Otros cultivos transitorios n.c.p.', 'A', '01'),
  ('0121', 'Cultivo de frutas tropicales y subtropicales', 'A', '01'),
  ('0122', 'Cultivo de plátano y banano', 'A', '01'),
  ('0123', 'Cultivo de café', 'A', '01'),
  ('0124', 'Cultivo de caña de azúcar', 'A', '01'),
  ('0125', 'Cultivo de flor de corte', 'A', '01'),
  ('0126', 'Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos', 'A', '01'),
  ('0127', 'Cultivo de plantas con las que se prepararan bebidas', 'A', '01'),
  ('0128', 'Cultivo de especias y de plantas aromáticas y medicinales', 'A', '01'),
  ('0129', 'Otros cultivos permanentes n.c.p.', 'A', '01'),
  ('0130', 'Propagación de plantas (actividades de los viveros, excepto viveros
forestales)', 'A', '01'),
  ('0141', 'Cría de ganado bovino y bufalino', 'A', '01'),
  ('0142', 'Cría de caballos y otros equinos', 'A', '01'),
  ('0143', 'Cría de ovejas y cabras', 'A', '01'),
  ('0144', 'Cría de ganado porcino', 'A', '01'),
  ('0145', 'Cría de aves de corral', 'A', '01'),
  ('0149', 'Cría de otros animales n.c.p.', 'A', '01'),
  ('0150', 'Explotación primaria mixta (agrícola y pecuaria)', 'A', '01'),
  ('0161', 'Actividades de apoyo a la agricultura', 'A', '01'),
  ('0162', 'Actividades de apoyo a la ganadería', 'A', '01'),
  ('0163', 'Actividades posteriores a la cosecha', 'A', '01'),
  ('0164', 'Tratamiento de semillas para propagación', 'A', '01'),
  ('0170', 'Caza ordinaria y mediante trampas y actividades de servicios conexas', 'A', '01'),
  ('0210', 'Silvicultura y otras actividades forestales', 'A', '02'),
  ('0220', 'Extracción de madera', 'A', '02'),
  ('0230', 'Recolección de productos forestales diferentes a la madera', 'A', '02'),
  ('0240', 'Servicios de apoyo a la silvicultura', 'A', '02'),
  ('0311', 'Pesca marítima', 'A', '03'),
  ('0312', 'Pesca de agua dulce', 'A', '03'),
  ('0321', 'Acuicultura marítima', 'A', '03'),
  ('0322', 'Acuicultura de agua dulce', 'A', '03'),
  ('0510', 'Extracción de hulla (carbón de piedra)', 'B', '05'),
  ('0520', 'Extracción de carbón lignito', 'B', '05'),
  ('0610', 'Extracción de petróleo crudo', 'B', '06'),
  ('0620', 'Extracción de gas natural', 'B', '06'),
  ('0710', 'Extracción de minerales de hierro', 'B', '07'),
  ('0721', 'Extracción de minerales de uranio y de torio', 'B', '07'),
  ('0722', 'Extracción de oro y otros metales preciosos', 'B', '07'),
  ('0723', 'Extracción de minerales de níquel', 'B', '07'),
  ('0729', 'Extracción de otros minerales metalíferos no ferrosos n.c.p.', 'B', '07'),
  ('0811', 'Extracción de piedra, arena,
arcillas comunes, yeso y
anhidrita', 'B', '08'),
  ('0812', 'Extracción de arcillas de uso industrial, caliza, caolín y bentonitas', 'B', '08'),
  ('0820', 'Extracción de esmeraldas, piedras preciosas y semipreciosas', 'B', '08'),
  ('0891', 'Extracción de minerales para la fabricación de abonos y productos químicos', 'B', '08'),
  ('0892', 'Extracción de halita (sal)', 'B', '08'),
  ('0899', 'Extracción de otros minerales no metálicos n.c.p.', 'B', '08'),
  ('0910', 'Actividades de apoyo para la extracción de petróleo y de gas natural', 'B', '09'),
  ('0990', 'Actividades de apoyo para otras actividades de explotación de minas y canteras', 'B', '09'),
  ('1011', 'Procesamiento y conservación de carne y productos cárnicos', 'C', '10'),
  ('1012', 'Procesamiento y conservación de pescados, crustáceos y moluscos', 'C', '10'),
  ('1030', 'Elaboración de aceites y grasas de origen vegetal y animal', 'C', '10'),
  ('1051', 'Elaboración de productos de molinería', 'C', '10'),
  ('1052', 'Elaboración de almidones y productos derivados del almidón', 'C', '10'),
  ('1061', 'Trilla de café', 'C', '10'),
  ('1062', 'Descafeinado, tostión y molienda del café', 'C', '10'),
  ('1063', 'Elaboración de otros derivados del café', 'C', '10'),
  ('1071', 'Elaboración y refinación de azúcar', 'C', '10'),
  ('1072', 'Elaboración de panela', 'C', '10'),
  ('1081', 'Elaboración de productos de panadería', 'C', '10'),
  ('1082', 'Elaboración de cacao, chocolate y productos de confitería', 'C', '10'),
  ('1083', 'Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares', 'C', '10'),
  ('1084', 'Elaboración de comidas y platos preparados', 'C', '10'),
  ('1089', 'Elaboración de otros productos alimenticios n.c.p.', 'C', '10'),
  ('1090', 'Elaboración de alimentos preparados para animales', 'C', '10'),
  ('1101', 'Destilación, rectificación y mezcla de bebidas alcohólicas', 'C', '11'),
  ('1102', 'Elaboración de bebidas fermentadas no destiladas', 'C', '11'),
  ('1103', 'Producción de malta, elaboración de cervezas y otras bebidas malteadas', 'C', '11'),
  ('1104', 'Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas', 'C', '11'),
  ('1200', 'Elaboración de productos de tabaco', 'C', '12'),
  ('1311', 'Preparación e hilatura de fibras textiles', 'C', '13'),
  ('1312', 'Tejeduría de productos textiles', 'C', '13'),
  ('1313', 'Acabado de productos textiles', 'C', '13'),
  ('1391', 'Fabricación de tejidos de punto y ganchillo', 'C', '13'),
  ('1392', 'Confección de artículos con materiales textiles, excepto prendas de vestir', 'C', '13'),
  ('1393', 'Fabricación de tapetes y alfombras para pisos', 'C', '13'),
  ('1394', 'Fabricación de cuerdas, cordeles, cables, bramantes y redes', 'C', '13'),
  ('1399', 'Fabricación de otros artículos textiles n.c.p.', 'C', '13'),
  ('1410', 'Confección de prendas de vestir, excepto prendas de piel', 'C', '14'),
  ('1511', 'Curtido y recurtido de cueros; recurtido y teñido de pieles.', 'C', '15'),
  ('1512', 'Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería.', 'C', '15'),
  ('1513', 'Fabricación de artículos de viaje, bolsos de mano y artículos similares; artículos de talabartería y guarnicionería elaborados en otros materiales', 'C', '15'),
  ('1521', 'Fabricación de calzado de cuero y piel, con cualquier tipo de suela', 'C', '15'),
  ('1522', 'Fabricación de otros tipos de calzado, excepto calzado de cuero y piel', 'C', '15'),
  ('1523', 'Fabricación de partes del calzado', 'C', '15'),
  ('1610', 'Aserrado, acepillado e impregnación de la madera', 'C', '16'),
  ('1620', 'Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles', 'C', '16'),
  ('1630', 'Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción y para edificios', 'C', '16'),
  ('1640', 'Fabricación de recipientes de madera', 'C', '16'),
  ('1690', 'Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería', 'C', '16'),
  ('1701', 'Fabricación de pulpas (pastas) celulósicas; papel y cartón', 'C', '17'),
  ('1702', 'Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón.', 'C', '17'),
  ('1709', 'Fabricación de otros artículos de papel y cartón', 'C', '17'),
  ('1811', 'Actividades de impresión', 'C', '18'),
  ('1812', 'Actividades de servicios relacionados con la impresión', 'C', '18'),
  ('1820', 'Producción de copias a partir de grabaciones originales', 'C', '18'),
  ('1910', 'Fabricación de productos de hornos de coque', 'C', '19'),
  ('1921', 'Fabricación de productos de la refinación del petróleo', 'C', '19'),
  ('1922', 'Actividad de mezcla de combustibles', 'C', '19'),
  ('2011', 'Fabricación de sustancias y productos químicos básicos', 'C', '20'),
  ('2012', 'Fabricación de abonos y compuestos inorgánicos nitrogenados', 'C', '20'),
  ('2013', 'Fabricación de plásticos en formas primarias', 'C', '20'),
  ('2014', 'Fabricación de caucho sintético en formas primarias', 'C', '20'),
  ('2021', 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario', 'C', '20'),
  ('2022', 'Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas', 'C', '20'),
  ('2023', 'Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador', 'C', '20'),
  ('2029', 'Fabricación de otros productos químicos n.c.p.', 'C', '20'),
  ('2030', 'Fabricación de fibras sintéticas y artificiales', 'C', '20'),
  ('2100', 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico', 'C', '21'),
  ('2211', 'Fabricación de llantas y neumáticos de caucho', 'C', '22'),
  ('2212', 'Reencauche de llantas usadas', 'C', '22'),
  ('2219', 'Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.', 'C', '22'),
  ('2221', 'Fabricación de formas básicas de plástico', 'C', '22'),
  ('2229', 'Fabricación de artículos de plástico n.c.p.', 'C', '22'),
  ('2310', 'Fabricación de vidrio y productos de vidrio', 'C', '23'),
  ('2391', 'Fabricación de productos refractarios', 'C', '23'),
  ('2392', 'Fabricación de materiales de arcilla para la construcción', 'C', '23'),
  ('2393', 'Fabricación de otros productos de cerámica y porcelana', 'C', '23'),
  ('2394', 'Fabricación de cemento, cal  y yeso', 'C', '23'),
  ('2395', 'Fabricación de artículos de hormigón, cemento y yeso', 'C', '23'),
  ('2396', 'Corte, tallado y acabado de la piedra', 'C', '23'),
  ('2399', 'Fabricación de otros productos minerales no metálicos n.c.p.', 'C', '23'),
  ('2410', 'Industrias básicas de hierro y de acero', 'C', '24'),
  ('2421', 'Industrias básicas de metales preciosos', 'C', '24'),
  ('2429', 'Industrias básicas de otros metales no ferrosos', 'C', '24'),
  ('2431', 'Fundición de hierro y de acero', 'C', '24'),
  ('2432', 'Fundición de metales no ferrosos', 'C', '24'),
  ('2511', 'Fabricación de productos metálicos para uso estructural', 'C', '25'),
  ('2512', 'Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías', 'C', '25'),
  ('2513', 'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central', 'C', '25'),
  ('2520', 'Fabricación de armas y municiones', 'C', '25'),
  ('2591', 'Forja, prensado, estampado y laminado de metal; pulvimetalurgia', 'C', '25'),
  ('2592', 'Tratamiento y revestimiento
de metales; mecanizado', 'C', '25'),
  ('2593', 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería', 'C', '25'),
  ('2599', 'Fabricación de otros productos elaborados de metal n.c.p.', 'C', '25'),
  ('2610', 'Fabricación de componentes y tableros electrónicos', 'C', '26'),
  ('2620', 'Fabricación de computadoras y de equipo periférico', 'C', '26'),
  ('2630', 'Fabricación de equipos de comunicación', 'C', '26'),
  ('2640', 'Fabricación de aparatos electrónicos de consumo', 'C', '26'),
  ('2651', 'Fabricación de equipo de medición, prueba, navegación y control', 'C', '26'),
  ('2652', 'Fabricación de relojes', 'C', '26'),
  ('2660', 'Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico', 'C', '26'),
  ('2670', 'Fabricación de instrumentos ópticos y equipo fotográfico', 'C', '26'),
  ('2680', 'Fabricación de soportes magnéticos y ópticos', 'C', '26'),
  ('2711', 'Fabricación de motores, generadores y transformadores eléctricos.', 'C', '27'),
  ('2712', 'Fabricación de aparatos de distribución y control de la energía eléctrica', 'C', '27'),
  ('2720', 'Fabricación de pilas, baterías y acumuladores eléctricos', 'C', '27'),
  ('2731', 'Fabricación de hilos y cables eléctricos y de fibra óptica', 'C', '27'),
  ('2732', 'Fabricación de dispositivos de cableado', 'C', '27'),
  ('2740', 'Fabricación de equipos eléctricos de iluminación', 'C', '27'),
  ('2750', 'Fabricación de aparatos de uso doméstico', 'C', '27'),
  ('2790', 'Fabricación de otros tipos de equipo eléctrico n.c.p.', 'C', '27'),
  ('2811', 'Fabricación de motores, turbinas, y partes para motores de combustión interna', 'C', '28'),
  ('2812', 'Fabricación de equipos de potencia hidráulica y neumática', 'C', '28'),
  ('2813', 'Fabricación de otras bombas, compresores, grifos y válvulas', 'C', '28'),
  ('2814', 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión', 'C', '28'),
  ('2815', 'Fabricación de hornos, hogares y quemadores industriales', 'C', '28'),
  ('2816', 'Fabricación de equipo de elevación y manipulación', 'C', '28'),
  ('2817', 'Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)', 'C', '28'),
  ('2818', 'Fabricación de herramientas manuales con motor', 'C', '28'),
  ('2819', 'Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p.', 'C', '28'),
  ('2821', 'Fabricación de maquinaria agropecuaria y forestal', 'C', '28'),
  ('2822', 'Fabricación de máquinas formadoras de metal y de máquinas herramienta', 'C', '28'),
  ('2823', 'Fabricación de maquinaria para la metalurgia', 'C', '28'),
  ('2824', 'Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción', 'C', '28'),
  ('2825', 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco', 'C', '28'),
  ('2826', 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros', 'C', '28'),
  ('2829', 'Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.', 'C', '28'),
  ('2910', 'Fabricación de vehículos automotores y sus motores', 'C', '29'),
  ('2920', 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques', 'C', '29'),
  ('2930', 'Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores', 'C', '29'),
  ('3011', 'Construcción de barcos y de estructuras flotantes', 'C', '30'),
  ('3012', 'Construcción de embarcaciones de recreo y deporte', 'C', '30'),
  ('3020', 'Fabricación de locomotoras y de material rodante para ferrocarriles', 'C', '30'),
  ('3030', 'Fabricación de aeronaves, naves espaciales y de maquinaria conexa', 'C', '30'),
  ('3040', 'Fabricación de vehículos militares de combate', 'C', '30'),
  ('3091', 'Fabricación de motocicletas', 'C', '30'),
  ('3092', 'Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad', 'C', '30'),
  ('3099', 'Fabricación de otros tipos de equipo de transporte n.c.p.', 'C', '30'),
  ('3110', 'Fabricación de muebles', 'C', '31'),
  ('3120', 'Fabricación de colchones y somieres', 'C', '31'),
  ('3210', 'Fabricación de joyas, bisutería y artículos conexos', 'C', '32'),
  ('3220', 'Fabricación de instrumentos musicales', 'C', '32'),
  ('3230', 'Fabricación de artículos y
equipo para la práctica del
deporte (excepto prendas
de vestir y calzado)', 'C', '32'),
  ('3240', 'Fabricación de juegos,
juguetes y rompecabezas', 'C', '32'),
  ('3250', 'Fabricación de
instrumentos, aparatos y
materiales médicos y
odontológicos (incluido
mobiliario)', 'C', '32'),
  ('3290', 'Otras industrias manufactureras n.c.p.', 'C', '32'),
  ('3311', 'Mantenimiento y reparación especializado de productos elaborados en metal', 'C', '33'),
  ('3312', 'Mantenimiento y reparación especializado de maquinaria y equipo', 'C', '33'),
  ('3313', 'Mantenimiento y reparación especializado de equipo electrónico y óptico', 'C', '33'),
  ('3314', 'Mantenimiento y reparación especializado de equipo eléctrico', 'C', '33'),
  ('3315', 'Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas', 'C', '33'),
  ('3319', 'Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.', 'C', '33'),
  ('3320', 'Instalación especializada de maquinaria y equipo industrial', 'C', '33'),
  ('3511', 'Generación de energía eléctrica', 'D', '35'),
  ('3512', 'Transmisión de energía eléctrica', 'D', '35'),
  ('3513', 'Distribución de energía eléctrica', 'D', '35'),
  ('3514', 'Comercialización de energía eléctrica', 'D', '35'),
  ('3530', 'Suministro de vapor y aire acondicionado', 'D', '35'),
  ('3700', 'Evacuación y tratamiento de aguas residuales', 'E', '37'),
  ('3811', 'Recolección de desechos no peligrosos', 'E', '38'),
  ('3812', 'Recolección de desechos peligrosos', 'E', '38'),
  ('3821', 'Tratamiento y disposición de desechos no peligrosos', 'E', '38'),
  ('3822', 'Tratamiento y disposición de desechos peligrosos', 'E', '38'),
  ('3830', 'Recuperación de materiales', 'E', '38'),
  ('4111', 'Construcción de edificios residenciales', 'F', '41'),
  ('4112', 'Construcción de edificios no residenciales', 'F', '41'),
  ('4210', 'Construcción de carreteras y vías de ferrocarril', 'F', '42'),
  ('4220', 'Construcción de proyectos de servicio público', 'F', '42'),
  ('4290', 'Construcción de otras obras de ingeniería civil', 'F', '42'),
  ('4311', 'Demolición', 'F', '43'),
  ('4312', 'Preparación del terreno', 'F', '43'),
  ('4321', 'Instalaciones eléctricas de la construcción', 'F', '43'),
  ('4322', 'Instalaciones de fontanería, calefacción y aire acondicionado de la construcción', 'F', '43'),
  ('4329', 'Otras instalaciones especializadas de la construcción', 'F', '43'),
  ('4330', 'Terminación y acabado de edificios y obras de ingeniería civil', 'F', '43'),
  ('4390', 'Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil', 'F', '43'),
  ('4511', 'Comercio de vehículos automotores nuevos', 'G', '45'),
  ('4512', 'Comercio de vehículos automotores usados', 'G', '45'),
  ('4520', 'Mantenimiento y reparación de vehículos automotores.', 'G', '45'),
  ('4530', 'Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores', 'G', '45'),
  ('4542', 'Mantenimiento y reparación de motocicletas y de sus partes y piezas', 'G', '45'),
  ('4610', 'Comercio al por mayor a cambio de una retribución o por contrata', 'G', '46'),
  ('4631', 'Comercio al por mayor de productos alimenticios', 'G', '46'),
  ('4641', 'Comercio al por mayor de productos textiles y productos confeccionados para uso doméstico', 'G', '46'),
  ('4642', 'Comercio al por mayor de prendas de vestir', 'G', '46'),
  ('4643', 'Comercio al por mayor de calzado', 'G', '46'),
  ('4644', 'Comercio al por mayor de aparatos y equipo de uso doméstico', 'G', '46'),
  ('4651', 'Comercio al por mayor de computadores, equipo periférico y programas de informática', 'G', '46'),
  ('4652', 'Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones', 'G', '46'),
  ('4653', 'Comercio al por mayor de maquinaria y equipo agropecuarios', 'G', '46'),
  ('4659', 'Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.', 'G', '46'),
  ('4662', 'Comercio al por mayor de metales y productos metalíferos', 'G', '46'),
  ('4664', 'Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario', 'G', '46'),
  ('4665', 'Comercio al por mayor de desperdicios, desechos y chatarra', 'G', '46'),
  ('4669', 'Comercio al por mayor de otros productos n.c.p.', 'G', '46'),
  ('4690', 'Comercio al por mayor no especializado', 'G', '46'),
  ('4721', 'Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados', 'G', '47'),
  ('4722', 'Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados', 'G', '47'),
  ('4723', 'Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados', 'G', '47'),
  ('4729', 'Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados', 'G', '47'),
  ('4731', 'Comercio al por menor de combustible para automotores', 'G', '47'),
  ('4732', 'Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores', 'G', '47'),
  ('4741', 'Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados', 'G', '47'),
  ('4742', 'Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados', 'G', '47'),
  ('4751', 'Comercio al por menor de productos textiles en establecimientos especializados', 'G', '47'),
  ('4753', 'Comercio al por menor de tapices, alfombras y recubrimientos para paredes y pisos en establecimientos especializados', 'G', '47'),
  ('4754', 'Comercio al por menor de electrodomésticos y gasodomésticos de uso doméstico, muebles y equipos de iluminación en establecimientos especializados', 'G', '47'),
  ('4755', 'Comercio al por menor de artículos y utensilios de uso doméstico en establecimientos especializados', 'G', '47'),
  ('4759', 'Comercio al por menor de otros artículos domésticos en establecimientos especializados', 'G', '47'),
  ('4762', 'Comercio al por menor de artículos deportivos, en establecimientos especializados', 'G', '47'),
  ('4769', 'Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados', 'G', '47'),
  ('4771', 'Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados', 'G', '47'),
  ('4772', 'Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados.', 'G', '47'),
  ('4774', 'Comercio al por menor de otros productos nuevos en establecimientos especializados', 'G', '47'),
  ('4775', 'Comercio al por menor de artículos de segunda mano', 'G', '47'),
  ('4782', 'Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles', 'G', '47'),
  ('4789', 'Comercio al por menor de otros productos en puestos de venta móviles', 'G', '47'),
  ('4911', 'Transporte férreo de pasajeros', 'H', '49'),
  ('4912', 'Transporte férreo de carga', 'H', '49'),
  ('4921', 'Transporte de pasajeros', 'H', '49'),
  ('4922', 'Transporte mixto', 'H', '49'),
  ('4923', 'Transporte de carga por carretera', 'H', '49'),
  ('4930', 'Transporte por tuberías', 'H', '49'),
  ('5011', 'Transporte de pasajeros marítimo y de cabotaje', 'H', '50'),
  ('5012', 'Transporte de carga
marítimo y de cabotaje', 'H', '50'),
  ('5021', 'Transporte fluvial de pasajeros', 'H', '50'),
  ('5022', 'Transporte fluvial de carga', 'H', '50'),
  ('5111', 'Transporte aéreo nacional de pasajeros', 'H', '51'),
  ('5112', 'Transporte aéreo internacional de pasajeros', 'H', '51'),
  ('5121', 'Transporte aéreo nacional de carga', 'H', '51'),
  ('5122', 'Transporte aéreo internacional de carga', 'H', '51'),
  ('5210', 'Almacenamiento y depósito', 'H', '52'),
  ('5221', 'Actividades de estaciones, vías y servicios complementarios para el transporte terrestre', 'H', '52'),
  ('5222', 'Actividades de puertos y servicios complementarios para el transporte acuático', 'H', '52'),
  ('5223', 'Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo', 'H', '52'),
  ('5224', 'Manipulación de carga', 'H', '52'),
  ('5229', 'Otras actividades complementarias al transporte', 'H', '52'),
  ('5310', 'Actividades postales nacionales', 'H', '53'),
  ('5320', 'Actividades de mensajería', 'H', '53'),
  ('5330', 'Servicio de pedido, compra, distribución y entrega de productos a través de plataformas o aplicaciones de contacto y que utilizan una red de domiciliarios', 'H', '53'),
  ('5511', 'Alojamiento en hoteles', 'I', '55'),
  ('5512', 'Alojamiento en aparta-hoteles', 'I', '55'),
  ('5513', 'Alojamiento en centros vacacionales', 'I', '55'),
  ('5514', 'Alojamiento rural', 'I', '55'),
  ('5519', 'Otros tipos de alojamientos para visitantes', 'I', '55'),
  ('5520', 'Actividades de zonas de camping y parques para vehículos recreacionales', 'I', '55'),
  ('5530', 'Servicio por horas  de alojamiento', 'I', '55'),
  ('5590', 'Otros tipos de alojamiento n.c.p.', 'I', '55'),
  ('5611', 'Expendio a la mesa de comidas preparadas', 'I', '56'),
  ('5612', 'Expendio por autoservicio de comidas preparadas', 'I', '56'),
  ('5613', 'Expendio de comidas preparadas en cafeterías', 'I', '56'),
  ('5619', 'Otros tipos de expendio de comidas preparadas n.c.p.', 'I', '56'),
  ('5621', 'Catering para eventos', 'I', '56'),
  ('5629', 'Actividades de otros servicios de comidas', 'I', '56'),
  ('5630', 'Expendio de bebidas alcohólicas para el consumo dentro del establecimiento', 'I', '56'),
  ('5812', 'Edición de directorios y listas de correo', 'J', '58'),
  ('5813', 'Edición de periódicos, revistas y otras publicaciones periódicas', 'J', '58'),
  ('5819', 'Otros trabajos de edición', 'J', '58'),
  ('5820', 'Edición de programas de informática (software)', 'J', '58'),
  ('5911', 'Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión (excepto programación de televisión)', 'J', '59'),
  ('5912', 'Actividades de postproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión (excepto programación de televisión)', 'J', '59'),
  ('5913', 'Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión', 'J', '59'),
  ('5914', 'Actividades de exhibición de películas cinematográficas y videos', 'J', '59'),
  ('5920', 'Actividades de grabación de sonido y edición de música', 'J', '59'),
  ('6010', 'Actividades de programación y transmisión en el servicio de radiodifusión sonora', 'J', '60'),
  ('6110', 'Actividades de telecomunicaciones alámbricas', 'J', '61'),
  ('6120', 'Actividades de telecomunicaciones inalámbricas', 'J', '61'),
  ('6130', 'Actividades de telecomunicación satelital', 'J', '61'),
  ('6190', 'Otras actividades de telecomunicaciones', 'J', '61'),
  ('6201', 'Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas)', 'J', '62'),
  ('6202', 'Actividades de consultoría informática y actividades de administración de instalaciones informáticas', 'J', '62'),
  ('6209', 'Otras actividades de tecnologías de información y actividades de servicios informáticos', 'J', '62'),
  ('6311', 'Procesamiento de datos, alojamiento (hosting) y actividades relacionadas', 'J', '63'),
  ('6312', 'Portales Web', 'J', '63'),
  ('6391', 'Actividades de agencias de noticias', 'J', '63'),
  ('6399', 'Otras actividades de servicio de información n.c.p.', 'J', '63'),
  ('6411', 'Banca Central', 'K', '64'),
  ('6412', 'Bancos comerciales', 'K', '64'),
  ('6421', 'Actividades de las corporaciones financieras', 'K', '64'),
  ('6422', 'Actividades de las compañías de financiamiento', 'K', '64'),
  ('6423', 'Banca de segundo piso', 'K', '64'),
  ('6424', 'Actividades de las cooperativas financieras', 'K', '64'),
  ('6431', 'Fideicomisos, fondos y entidades financieras similares', 'K', '64'),
  ('6491', 'Leasing financiero (arrendamiento financiero)', 'K', '64'),
  ('6492', 'Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario', 'K', '64'),
  ('6493', 'Actividades de compra de cartera o factoring', 'K', '64'),
  ('6494', 'Otras actividades de distribución de fondos', 'K', '64'),
  ('6495', 'Instituciones especiales oficiales', 'K', '64'),
  ('6496', 'Capitalización', 'K', '64'),
  ('6511', 'Seguros generales', 'K', '65'),
  ('6512', 'Seguros de vida', 'K', '65'),
  ('6513', 'Reaseguros', 'K', '65'),
  ('6515', 'Seguros de salud', 'K', '65'),
  ('6521', 'Servicios de seguros sociales de salud', 'K', '65'),
  ('6522', 'Servicios de seguros sociales en riesgos laborales', 'K', '65'),
  ('6523', 'Servicios de seguros sociales en riesgos familia', 'K', '65'),
  ('6531', 'Régimen de prima media con prestación definida (RPM)', 'K', '65'),
  ('6532', 'Régimen de ahorro con solidaridad (RAIS)', 'K', '65'),
  ('6612', 'Corretaje de valores y de contratos de productos básicos', 'K', '66'),
  ('6613', 'Otras actividades relacionadas con el mercado de valores', 'K', '66'),
  ('6614', 'Actividades de las sociedades de intermediación cambiaria y de servicios financieros especiales', 'K', '66'),
  ('6615', 'Actividades de los profesionales de compra y venta de divisas', 'K', '66'),
  ('6619', 'Otras actividades auxiliares de las actividades de servicios financieros n.c.p.', 'K', '66'),
  ('6621', 'Actividades de agentes y corredores de seguros', 'K', '66'),
  ('6629', 'Evaluación de riesgos y daños, y otras actividades de servicios auxiliares', 'K', '66'),
  ('6630', 'Actividades de administración de fondos', 'K', '66'),
  ('6810', 'Actividades inmobiliarias realizadas con bienes propios o arrendados', 'L', '68'),
  ('6820', 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata', 'L', '68'),
  ('7310', 'Publicidad', 'M', '73'),
  ('7420', 'Actividades de fotografía', 'M', '74'),
  ('7500', 'Actividades veterinarias', 'M', '75'),
  ('7710', 'Alquiler y arrendamiento de vehículos automotores', 'N', '77'),
  ('7721', 'Alquiler y arrendamiento de equipo recreativo y deportivo', 'N', '77'),
  ('7722', 'Alquiler de videos y discos', 'N', '77'),
  ('7729', 'Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.', 'N', '77'),
  ('7730', 'Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.', 'N', '77'),
  ('7740', 'Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor', 'N', '77'),
  ('7810', 'Actividades de agencias de gestión y colocación de empleo', 'N', '78'),
  ('7820', 'Actividades de empresas de servicios temporales', 'N', '78'),
  ('7830', 'Otras actividades de provisión de talento humano', 'N', '78'),
  ('7911', 'Actividades de las agencias de viaje', 'N', '79'),
  ('7912', 'Actividades de operadores turísticos', 'N', '79'),
  ('7990', 'Otros servicios de reserva y actividades relacionadas', 'N', '79'),
  ('8010', 'Actividades de seguridad privada', 'N', '80'),
  ('8020', 'Actividades de servicios de sistemas de seguridad', 'N', '80'),
  ('8030', 'Actividades de detectives e investigadores privados', 'N', '80'),
  ('8110', 'Actividades combinadas de apoyo a instalaciones', 'N', '81'),
  ('8121', 'Limpieza general interior de edificios', 'N', '81'),
  ('8129', 'Otras actividades de limpieza de edificios e instalaciones industriales', 'N', '81'),
  ('8130', 'Actividades de paisajismo y servicios de mantenimiento conexos', 'N', '81'),
  ('8211', 'Actividades combinadas de servicios administrativos de oficina', 'N', '82'),
  ('8219', 'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina', 'N', '82'),
  ('8220', 'Actividades de centros de llamadas (Call center)', 'N', '82'),
  ('8230', 'Organización de convenciones y eventos comerciales', 'N', '82'),
  ('8291', 'Actividades de agencias de cobranza y oficinas de calificación crediticia', 'N', '82'),
  ('8292', 'Actividades de envase y empaque', 'N', '82'),
  ('8299', 'Otras actividades de servicio de apoyo a las empresas n.c.p.', 'N', '82'),
  ('8411', 'Actividades legislativas de la administración pública', 'O', '84'),
  ('8412', 'Actividades ejecutivas de la administración pública', 'O', '84'),
  ('8413', 'Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social', 'O', '84'),
  ('8414', 'Actividades reguladoras y facilitadoras de la actividad económica', 'O', '84'),
  ('8415', 'Actividades de los órganos de control y otras instituciones.', 'O', '84'),
  ('8421', 'Relaciones exteriores', 'O', '84'),
  ('8422', 'Actividades de defensa', 'O', '84'),
  ('8423', 'Orden público y actividades de seguridad publica', 'O', '84'),
  ('8424', 'Administración de justicia', 'O', '84'),
  ('8430', 'Actividades de planes de Seguridad Social de afiliación obligatoria', 'O', '84'),
  ('8511', 'Educación de la primera infancia', 'P', '85'),
  ('8512', 'Educación preescolar', 'P', '85'),
  ('8513', 'Educación básica primaria', 'P', '85'),
  ('8521', 'Educación básica secundaria', 'P', '85'),
  ('8522', 'Educación media académica', 'P', '85'),
  ('8523', 'Educación media técnica', 'P', '85'),
  ('8530', 'Establecimientos que combinan diferentes niveles de educación inicial, preescolar, básica primaria, básica secundaria y media', 'P', '85'),
  ('8541', 'Educación técnica profesional', 'P', '85'),
  ('8542', 'Educación tecnológica', 'P', '85'),
  ('8543', 'Educación de instituciones universitarias o de escuelas tecnológicas', 'P', '85'),
  ('8544', 'Educación de universidades', 'P', '85'),
  ('8551', 'Formación para el trabajo', 'P', '85'),
  ('8552', 'Enseñanza deportiva y recreativa', 'P', '85'),
  ('8553', 'Enseñanza cultural', 'P', '85'),
  ('8559', 'Otros tipos de educación n.c.p.', 'P', '85'),
  ('8560', 'Actividades de apoyo a la educación', 'P', '85'),
  ('8610', 'Actividades de hospitales y clínicas, con internación', 'Q', '86'),
  ('8720', 'Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas', 'Q', '87'),
  ('8730', 'Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas', 'Q', '87'),
  ('8790', 'Otras actividades de atención en instituciones con alojamiento', 'Q', '87'),
  ('8810', 'Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas', 'Q', '88'),
  ('8891', 'Actividades de guarderías para niños y niñas', 'Q', '88'),
  ('8899', 'Otras actividades de asistencia social n.c.p', 'Q', '88'),
  ('9001', 'Creación literaria', 'R', '90'),
  ('9002', 'Creación musical', 'R', '90'),
  ('9003', 'Creación teatral', 'R', '90'),
  ('9004', 'Creación audiovisual', 'R', '90'),
  ('9005', 'Artes plásticas y visuales', 'R', '90'),
  ('9006', 'Actividades teatrales', 'R', '90'),
  ('9007', 'Actividades de espectáculos musicales en vivo', 'R', '90'),
  ('9008', 'Otras actividades de espectáculos en vivo n.c.p', 'R', '90'),
  ('9101', 'Actividades de Bibliotecas y archivos', 'R', '91'),
  ('9102', 'Actividades y funcionamiento de museos, conservación de edificios y sitios históricos', 'R', '91'),
  ('9103', 'Actividades de jardines botánicos, zoológicos y reservas naturales', 'R', '91'),
  ('9311', 'Gestión de instalaciones deportivas', 'R', '93'),
  ('9312', 'Actividades de clubes deportivos', 'R', '93'),
  ('9319', 'Otras actividades deportivas', 'R', '93'),
  ('9321', 'Actividades de parques de atracciones y parques temáticos', 'R', '93'),
  ('9411', 'Actividades de asociaciones empresariales y de empleadores', 'S', '94'),
  ('9412', 'Actividades de asociaciones profesionales y gremiales sin ánimo de lucro', 'S', '94'),
  ('9420', 'Actividades de sindicatos', 'S', '94'),
  ('9491', 'Actividades de asociaciones religiosas', 'S', '94'),
  ('9492', 'Actividades de partidos políticos', 'S', '94'),
  ('9499', 'Actividades de otras asociaciones n.c.p.', 'S', '94'),
  ('9511', 'Mantenimiento y reparación de computadores y de equipo periférico', 'S', '95'),
  ('9512', 'Mantenimiento y reparación de equipos de comunicación', 'S', '95'),
  ('9521', 'Mantenimiento y reparación de aparatos electrónicos de consumo', 'S', '95'),
  ('9522', 'Mantenimiento y reparación de aparatos domésticos y equipos domésticos y de jardinería', 'S', '95'),
  ('9523', 'Reparación de calzado y artículos de cuero', 'S', '95'),
  ('9524', 'Reparación de muebles y accesorios para el hogar', 'S', '95'),
  ('9529', 'Mantenimiento y reparación de otros efectos personales y enseres domésticos', 'S', '95'),
  ('9601', 'Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel', 'S', '96'),
  ('9602', 'Peluquería y otros tratamientos de belleza', 'S', '96'),
  ('9603', 'Pompas fúnebres y actividades relacionadas', 'S', '96'),
  ('9609', 'Otras actividades de servicios personales n.c.p.', 'S', '96'),
  ('9700', 'Actividades de los hogares individuales como empleadores de personal doméstico', 'T', '97'),
  ('9810', 'Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio', 'T', '98'),
  ('9820', 'Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio', 'T', '98'),
  ('9900', 'Actividades de organizaciones y entidades extraterritoriales signatarios de la Convención de Viena', 'U', '99')
) AS v(codigo, nombre, seccion, division)
WHERE NOT EXISTS (
  SELECT 1 FROM ciiu_activity e
   WHERE e.tenant_id IS NULL AND e.company_id IS NULL AND e.codigo = v.codigo
);
